services:
  scraper:
    image: cdmanning/web-scrape-notifier:latest
    container_name: Web-Scrape-Notifier
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json:ro
    #build:
    #  context: .
    #  dockerfile: Dockerfile
